// cards.js
// Converted from original flat array format into structured objects

const cards = [
  // Radicals 1
  { set: "Radicals 1", hanzi: "中", pinyin: "zhōng", gloss: "middle" },
  { set: "Radicals 1", hanzi: "人", pinyin: "rén", gloss: "person" },
  { set: "Radicals 1", hanzi: "大", pinyin: "dà", gloss: "big" },
  { set: "Radicals 1", hanzi: "止", pinyin: "zhǐ", gloss: "stop" },
  { set: "Radicals 1", hanzi: "火", pinyin: "huǒ", gloss: "fire" },
  { set: "Radicals 1", hanzi: "化", pinyin: "huà", gloss: "change" },
  { set: "Radicals 1", hanzi: "车", pinyin: "chē", gloss: "car" },
  { set: "Radicals 1", hanzi: "失", pinyin: "shǐ", gloss: "arrow" },
  { set: "Radicals 1", hanzi: "水", pinyin: "shuǐ", gloss: "water" },
  { set: "Radicals 1", hanzi: "千", pinyin: "qiān", gloss: "1000" },
  { set: "Radicals 1", hanzi: "川", pinyin: "chuān", gloss: "river" },
  { set: "Radicals 1", hanzi: "巾", pinyin: "jīn", gloss: "towel" },
  { set: "Radicals 1", hanzi: "门", pinyin: "mén", gloss: "gate" },
  { set: "Radicals 1", hanzi: "白", pinyin: "bái", gloss: "white" },
  { set: "Radicals 1", hanzi: "竹", pinyin: "zhú", gloss: "bamboo" },
  { set: "Radicals 1", hanzi: "目", pinyin: "mù", gloss: "eye" },
  { set: "Radicals 1", hanzi: "心", pinyin: "xīn", gloss: "heart" },
  { set: "Radicals 1", hanzi: "工", pinyin: "gōng", gloss: "work" },
  { set: "Radicals 1", hanzi: "手", pinyin: "shǒu", gloss: "hand" },
  { set: "Radicals 1", hanzi: "木", pinyin: "mù", gloss: "tree" },
  { set: "Radicals 1", hanzi: "入", pinyin: "rù", gloss: "enter" },
  { set: "Radicals 1", hanzi: "又", pinyin: "yòu", gloss: "again" },
  { set: "Radicals 1", hanzi: "山", pinyin: "shān", gloss: "mountain" },
  { set: "Radicals 1", hanzi: "比", pinyin: "bǐ", gloss: "compare" },
  { set: "Radicals 1", hanzi: "贝", pinyin: "bèi", gloss: "shell" },
  { set: "Radicals 1", hanzi: "爪", pinyin: "zhǎo", gloss: "claw" },
  { set: "Radicals 1", hanzi: "片", pinyin: "piàn", gloss: "sheet" },
  { set: "Radicals 1", hanzi: "寸", pinyin: "cún", gloss: "inch" },
  { set: "Radicals 1", hanzi: "干", pinyin: "gān", gloss: "oppose;dry" },
  { set: "Radicals 1", hanzi: "弓", pinyin: "gōng", gloss: "bow" },
  { set: "Radicals 1", hanzi: "方", pinyin: "fāng", gloss: "direction" },
  { set: "Radicals 1", hanzi: "子", pinyin: "zǐ", gloss: "child" },
  { set: "Radicals 1", hanzi: "米", pinyin: "mǐ", gloss: "rice" },
  { set: "Radicals 1", hanzi: "北", pinyin: "běi", gloss: "north" },
  { set: "Radicals 1", hanzi: "牛", pinyin: "niú", gloss: "cattle" },
  { set: "Radicals 1", hanzi: "云", pinyin: "yún", gloss: "cloud" },
  { set: "Radicals 1", hanzi: "文", pinyin: "wén", gloss: "writing" },
  { set: "Radicals 1", hanzi: "月", pinyin: "yuè", gloss: "moon" },
  { set: "Radicals 1", hanzi: "石", pinyin: "shí", gloss: "stone" },
  { set: "Radicals 1", hanzi: "风", pinyin: "fēng", gloss: "wind" },
  { set: "Radicals 1", hanzi: "玉", pinyin: "yù", gloss: "jade" },
  { set: "Radicals 1", hanzi: "王", pinyin: "wáng", gloss: "king" },
  { set: "Radicals 1", hanzi: "小", pinyin: "xiǎo", gloss: "small" },
  { set: "Radicals 1", hanzi: "口", pinyin: "kǒu", gloss: "mouth" },
  { set: "Radicals 1", hanzi: "毛", pinyin: "máo", gloss: "wool" },
  { set: "Radicals 1", hanzi: "甘", pinyin: "gān", gloss: "sweet" },
  { set: "Radicals 1", hanzi: "禾", pinyin: "hé", gloss: "grain" },
  { set: "Radicals 1", hanzi: "见", pinyin: "jiàn", gloss: "look" },
  { set: "Radicals 1", hanzi: "言", pinyin: "yán", gloss: "speech" },
  { set: "Radicals 1", hanzi: "自", pinyin: "zì", gloss: "self" },

  // Radicals 2
  { set: "Radicals 2", hanzi: "国", pinyin: "guó", gloss: "country" },
  { set: "Radicals 2", hanzi: "好", pinyin: "hâo", gloss: "good" },
  { set: "Radicals 2", hanzi: "两", pinyin: "liǎng", gloss: "pair" },
  { set: "Radicals 2", hanzi: "舌", pinyin: "shé", gloss: "tongue" },
  { set: "Radicals 2", hanzi: "多", pinyin: "duō", gloss: "many" }
  
  // (Continue same pattern for remaining entries)
];
